
--DROP table SQL_PROJ;
--DROP table CD_PROJECTS ;
--DROP table SQLINFO ;
--DROP table SQLMASTER;

CREATE TABLE SQLMASTER(
  SQL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  SQL_STRING VARCHAR(1000) NOT NULL,
  SEARCH_WORDS VARCHAR (50),
  COMMENTS VARCHAR(200)
);



CREATE TABLE SQLINFO(
  SQL_INFO_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SQL_ID BIGINT NOT NULL,
  VAR_TYPE VARCHAR(64), -- ACCOUNT NO, FL_NBR ETC...
  VAR_VALUE VARCHAR(64), -- -INT, STRING , DATE ETC...
  COMMENTS VARCHAR(200)
);

CREATE TABLE SQL_PROJ(
  PROJ_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SQL_ID BIGINT NOT NULL
);

CREATE TABLE CD_PROJECTS(
  PROJ_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  PROJ_NAME VARCHAR (25)
);

ALTER TABLE SQLINFO ADD FOREIGN KEY (SQL_ID) REFERENCES SQLMASTER(SQL_ID);
ALTER TABLE SQL_PROJ ADD FOREIGN KEY (SQL_ID) REFERENCES SQLMASTER(SQL_ID);